<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\Yamaha.Psg.Core\Yamaha.Psg.Core.csproj" />
    <ProjectReference Include="..\Yamaha.Psg.Formats\Yamaha.Psg.Formats.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="NAudio" Version="2.3.0" />
  </ItemGroup>

  <PropertyGroup>
    <OutputType>Exe</OutputType>
  </PropertyGroup>

</Project>
